In [6]:
import os
import sys
import collections
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
src_dir = os.path.join("src")
sys.path.insert(0, src_dir)
from trainer import VideoTrainer
from utils import init, DotDict
from parse_config import ConfigParser
from model import VTNBuilder

In [7]:
def update(d, u):
    for k, v in u.items():
        if isinstance(v, collections.abc.Mapping):
            d[k] = update(d.get(k, {}), v)
        else:
            d[k] = v
    return d

In [8]:
args = DotDict({
    "resume": "saved/model_best"
})
config = ConfigParser.from_args(args)
update(config.config, {
    "data_loader":{
        "args": {
            "data_path": "data/orig-front-videos",
            "validation_split": 0.1,
            "shuffle": True
        }
    }
})
data_loader, model = init(config)

FileNotFoundError: [Errno 2] No such file or directory: 'saved/0722_055454/config.json'

In [ ]:
trainer = VideoTrainer(model, config, data_loader=data_loader)

In [ ]:
results, logit, gTruth = trainer.test()

  0%|          | 0/47 [00:06<?, ?it/s]


ValueError: Tensor's shape (288, 768) is not compatible with supplied shape [2, 768]

In [ ]:
results

{'loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.1238122>,
 'accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.16783217>}

In [ ]:
for l in logit:
    print(l.numpy().argmax(-1))

[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8]


In [ ]:
gTruth

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 3, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 8, 0], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 6, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 1, 5], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 8, 2], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 8, 8], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 2], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 4], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 5, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 0, 6], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 1, 7], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 8], dtype=int32)>,
 <tf.Tensor:

In [ ]:
for layer in model.layers:
    print(layer)