In [1]:
import os
import sys
import collections
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
src_dir = os.path.join("src")
sys.path.insert(0, src_dir)
from trainer import VideoTrainer
from utils import init, DotDict
from parse_config import ConfigParser
from model import VTNBuilder

In [2]:
def update(d, u):
    for k, v in u.items():
        if isinstance(v, collections.abc.Mapping):
            d[k] = update(d.get(k, {}), v)
        else:
            d[k] = v
    return d

In [3]:
args = DotDict({
    "resume": "saved/0722_055454/model_best"
})
config = ConfigParser.from_args(args)
update(config.config, {
    "data_loader":{
        "args": {
            "data_path": "data/orig-front-videos",
            "validation_split": 0.1,
            "shuffle": True
        }
    }
})
data_loader, model = init(config)

2021-07-21 23:20:23.163721: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
trainer = VideoTrainer(model, config, data_loader=data_loader)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
results, logit, gTruth = trainer.test()

  0%|          | 0/47 [00:00<?, ?it/s]2021-07-21 17:19:15.384047: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
Loss: 2.124: : 48it [02:56,  3.69s/it]


In [ ]:
results

{'loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.1238122>,
 'accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.16783217>}

In [ ]:
for l in logit:
    print(l.numpy().argmax(-1))

[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8]


In [ ]:
gTruth

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 3, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 8, 0], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 6, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 1, 5], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 8, 2], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 8, 8], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 2], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 4], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 5, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 0, 6], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 1, 7], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 8], dtype=int32)>,
 <tf.Tensor:

In [ ]:
for layer in model.layers:
    print(layer)